name: qingyu_bill
description: 轻语账单 - 纯本地语音记账 App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.9
  uuid: ^4.5.1
  intl: ^0.19.0
  speech_to_text: ^6.4.0

dev_dependencies:
  build_runner: ^2.4.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/capoo.svg